
services:


  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql




  backend_app:
    build:
      context: ./backend
    ports:
      - "8800:8800"
    environment:
      DB_HOST: mysql_db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: test
    depends_on:
      - mysql_db




  frontend_ui:
    environment:
      - PORT=5173
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend_app



volumes:
  db-data:
    driver: bridge
