name: chase-app-containerized

services:

# database service
  mySqlDb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -ppassword -e 'USE test;SELECT 1;'"]
      start_period: 2s
      interval: 3s
      timeout: 3s
      retries: 60
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - applicationNetwork

# frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - applicationNetwork

# backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    depends_on:
      mySqlDb:
        condition: service_healthy
    networks:
      - applicationNetwork
  
volumes:
  db_data:
  
networks:
  applicationNetwork:
    driver: bridge