
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: P@55w0rd!
      DB_NAME: test

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@55w0rd!
      MYSQL_DATABASE: test
      MYSQL_USER: chemch
      MYSQL_PASSWORD: P@55w0rd!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 

volumes:
  db_data:
